[versions]
androidGradlePlugin = "8.2.0"
kotlin = "1.9.21"
dokka = "1.9.10"
androidxNavigation = "2.7.5"
gradleVersionsPlugin = "0.49.0"
kotlinxCoroutines = "1.7.3"

[libraries]
# classPath
androidGradlePlugin = { group = "com.android.tools.build", name = "gradle", version.ref = "androidGradlePlugin" }
kotlinGradlePlugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
dokkaGradlePlugin = { group = "org.jetbrains.dokka", name = "dokka-gradle-plugin", version.ref = "dokka" }
gradleVersionsPlugin = { group = "com.github.ben-manes", name = "gradle-versions-plugin", version.ref = "gradleVersionsPlugin" }

# implementation
kotlinStdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlin" }
kotlinxCoroutinesAndroid = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "kotlinxCoroutines" }
androidxAppCompat = { group = "androidx.appcompat", name = "appcompat", version = "1.6.1" }
androidxConstraintLayout = { group = "androidx.constraintlayout", name = "constraintlayout", version = "2.1.4" }
androidxCoreKtx = { group = "androidx.core", name = "core-ktx", version = "1.12.0" }
androidxNavigationFragmentKtx = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "androidxNavigation" }
androidxNavigationUiKtx = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "androidxNavigation" }
materialComponents = { group = "com.google.android.material", name = "material", version = "1.10.0" }

# debugImplementation
leakCanary = { group = "com.squareup.leakcanary", name = "leakcanary-android", version = "2.12" }

# testImplementation
junit = { group = "junit", name = "junit", version = "4.13.2" }

# dokkaPlugin
dokkaAndroidDocumentationPlugin = { group = "org.jetbrains.dokka", name = "android-documentation-plugin", version.ref = "dokka" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "androidGradlePlugin" }
androidLibrary = { id = "com.android.library", version.ref = "androidGradlePlugin" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
navigationSafeArgs = { id = "androidx.navigation.safeargs.kotlin", version.ref = "androidxNavigation" }
gradleVersions = { id = "com.github.ben-manes.versions", version.ref = "gradleVersionsPlugin" }

[bundles]
plugins = [
    "androidGradlePlugin",
    "kotlinGradlePlugin",
    "dokkaGradlePlugin",
    "gradleVersionsPlugin",
]
